name: deploy-to-github-pages
run-name: Deploy dyad documentation to github pages
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: build
        run: yarn build
        working-directory: ./docs

